### ISSUE TITLE
The Parameter Size obtained under all quantization settings is 18.48MB

### ISSUE THREAD

**Issue by YanZhiyuan0918** [hossein1387/U-Net-Fixed-Point-Quantization-for-Medical-Image-Segmentation#3]
Hi,
Thanks for your good work. I have some questions when running the code:

The Parameter Size I obtained under all quantization settings is 18.48MB based on the EM dataset. According to your paper, The Parameter Size should be smaller than Full Precision. Could you please help me analyze the possible reasons? Thanks a lot!

For example, when I want to run UNET_EM_DATASET_a8_0_w0_8, the config.yaml is set to:
`UNET:`
`    dataset: 'emdataset'`
`lr: 0.001`
`num_epochs: 200`
`model_type: "unet"`
` init_type: glorot`
`quantization: "FIXED" # "INT", "BNN", "Normal", "FIXED"`
`activation_f_width: 0`
`activation_i_width: 6`
 ` weight_f_width: 4`
`weight_i_width: 0`
`gpu_core_num: 1`
`activation: "tanh"`
`  trained_model: "./em_tanh_a6_0_w0_4/em_tanh_a6_0_w0_4.pkl"`
` experiment_name: "em_tanh_a6_0_w0_4"`
`  log_output_dir: "./results/"`
` operation_mode: "normal" # normal, visualize, retrain, inference`

Then, I run the code:
`python em_unet.py -f config.yaml -t UNET`

The environment I use:
Linux
Python 3.5.2
Nvidia 2080Ti GPU

**Comment by YanZhiyuan0918** [comment]
Hi, sorry for disturbing you again. I would like to ask whether the "Parameter Size" in your paper equals to the "Model Size(.pkl)" saved in the training peocess?

**Comment by hossein1387** [comment]
Hi,
I just saw that you have created an issue. Sorry for my late response. Actually, at the time I was writing up the code, Pytorch did not had any support for quantization. So although you use 8 bit values in your model, it would still store them into 32 bit values. In the latest Pytorch release, they have added quantized tensors. I have quantized models with it and I can see the actual size of the model is reduced. However, in my case, since I am using custom number of bits (2,3,4 etc.) I cannot use pytorch quantized tensors since it only support for 8, 16 and 32 bit values. So I only can use fake quantization method + guestimating how big the final model will be. So to answer your question, no the model size of the pkl file is not what I mentioned in the paper.
